DIRECTORIES = 'directories'
STATIC_FOLDER = 'STATIC_FOLDER'
UPLOAD_FOLDER = 'UPLOAD_FOLDER'

NETWORK = 'network'
PORT = 'PORT'
RANDOMIZE_PORT = 'RANDOMIZE_PORT'

SAVING = 'saving'
ZIP_FILES = 'ZIP_FILES'

STRUCTURE = {
    DIRECTORIES: [(STATIC_FOLDER, str), (UPLOAD_FOLDER, str)],
    NETWORK: [(PORT, int), (RANDOMIZE_PORT, bool)],
    SAVING: [(ZIP_FILES, bool)],
}